sudo: required

services:
  - docker

before_install:
  - docker pull squidfunk/mkdocs-material

script:
  - docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build 

deploy:
  local-dir: site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: live
